const Types = {
  LIST_BY_USER_REQUEST: '@posts/LIST_BY_USER_REQUEST',
  LIST_BY_USER_FAILURE: '@posts/LIST_BY_USER_FAILURE',
  LIST_BY_USER_SUCCESS: '@posts/LIST_BY_USER_SUCCESS',
};

export default Types;
